#!/usr/bin/env bash

set -e

DEVICE="${DEVICE:-/dev/ttyACM1}"

stty -F "${DEVICE}" 9600 raw -echo

exec 3<"${DEVICE}"
echo "$@" >"${DEVICE}"

while read -r line <&3; do
    line="$(echo -n "${line}" | tr -d '\r')"
    if [ "${line}" == "." ]; then
        break
    fi
    echo "${line}"
done
